version: "3"
services:
  mongodb:
    image: mongo:4.2
    container_name: "mongodb"
    restart: unless-stopped
    hostname: app.database
    command: --replSet app --serviceExecutor adaptive --wiredTigerCacheSizeGB 2
    ports:
      - 27017:27017

  redis:
    image: redis
    ports:
      - "6379:6379"
